name: Mirror ke Repo Private (tanpa folder repo-private)

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo publik
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git identity
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Clone repo private ke folder sementara
        run: |
          git clone "${{ secrets.PRIVATE_REPO_URL }}" private-tmp

      - name: Sinkronisasi file ke private-tmp (tanpa config & workflow)
        run: |
          rsync -av \
            --exclude='.git' \
            --exclude='src/data/config.json' \
            --exclude='.github/workflows/' \
            ./ ./private-tmp/

          rsync -av ./public/ ./private-tmp/public/

      - name: Commit dan Push ke repo private
        run: |
          cd private-tmp
          git add .
          git commit -m "Sync from nikahfix (no repo-private folder, safe overwrite)" || echo "Nothing to commit"
          git push origin main
