name: Mirror ke Repo Private (tanpa config & workflows)

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo publik
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git identity
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Clone repo private
        run: |
          git clone "${{ secrets.PRIVATE_REPO_URL }}" ../private-repo
      - name: Sinkronisasi file ke repo private (tanpa overwrite file existing)
        run: |
          # Sinkronisasi semua file kecuali yang dikecualikan, tanpa overwrite existing files
          rsync -av \
            --exclude='.git' \
            --exclude='src/data/config.json' \
            --exclude='.github/' \
            --exclude='public/' \
            --ignore-existing \
            ./ ../private-repo/
          
          # Sinkronisasi folder public hanya untuk file baru (tidak overwrite existing)
          rsync -av \
            --ignore-existing \
            ./public/ ../private-repo/public/

      - name: Commit dan Push ke repo private
        run: |
          cd ../private-repo
          git add .
          git commit -m "Sync from nikahfix (excluding config & workflows)" || echo "Nothing to commit"
          git push origin main
